# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

from process.input import openfile


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(90, 330, 569, 159))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")

        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(300, 0, 281, 159))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")

        self.run = QtWidgets.QPushButton(self.groupBox_4)
        self.run.setGeometry(QtCore.QRect(60, 40, 161, 81))
        self.run.setObjectName("run")

        self.pushButton_ok = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_ok.setGeometry(QtCore.QRect(100, 110, 93, 28))
        self.pushButton_ok.setObjectName("pushButton_ok")

        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(50, 30, 203, 61))
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)

        self.repeat_times = QtWidgets.QSpinBox(self.widget)
        self.repeat_times.setObjectName("repeat_times")
        self.repeat_times.setRange(10, 100)
        self.repeat_times.setSingleStep(10)
        self.horizontalLayout_4.addWidget(self.repeat_times)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")

        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)

        self.man_times = QtWidgets.QSpinBox(self.widget)
        self.man_times.setObjectName("man_times")
        self.man_times.setRange(0, 10)
        self.man_times.setSingleStep(5)
        self.horizontalLayout_7.addWidget(self.man_times)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 80, 571, 161))
        self.layoutWidget.setObjectName("layoutWidget")

        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.groupBox_A = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_A.setObjectName("groupBox_A")

        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_A)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 110, 231, 41))
        self.layoutWidget1.setObjectName("layoutWidget1")

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")

        self.selectfile1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.selectfile1.clicked.connect(self.openfilename1) # 选择文件
        self.selectfile1.setObjectName("selectfile1")
        self.horizontalLayout_3.addWidget(self.selectfile1)

        self.file1_pre = QtWidgets.QPushButton(self.layoutWidget1)
        self.file1_pre.setObjectName("file1_pre")
        self.horizontalLayout_3.addWidget(self.file1_pre)

        self.file1_add = QtWidgets.QLineEdit(self.groupBox_A)
        self.file1_add.setGeometry(QtCore.QRect(30, 50, 221, 31))
        self.file1_add.setObjectName("file1_add")

        self.groupBox_B = QtWidgets.QGroupBox(self.groupBox_A)
        self.groupBox_B.setGeometry(QtCore.QRect(300, 0, 281, 159))
        self.groupBox_B.setObjectName("groupBox_B")

        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_B)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 110, 231, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.selectfile2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.selectfile2.clicked.connect(self.openfilename2)  # 选择文件
        self.selectfile2.setObjectName("selectfile2")
        self.horizontalLayout_2.addWidget(self.selectfile2)

        self.file2_pre = QtWidgets.QPushButton(self.layoutWidget2)
        self.file2_pre.setObjectName("file2_pre")
        self.horizontalLayout_2.addWidget(self.file2_pre)

        self.file2_add = QtWidgets.QLineEdit(self.groupBox_B)
        self.file2_add.setGeometry(QtCore.QRect(20, 50, 221, 31))
        self.file2_add.setObjectName("file2_add")

        self.horizontalLayout.addWidget(self.groupBox_A)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.run.setText(_translate("MainWindow", "开始演化"))
        self.pushButton_ok.setText(_translate("MainWindow", "确定"))
        self.label.setText(_translate("MainWindow", "设置迭代次数       "))
        self.label_2.setText(_translate("MainWindow", "设置交互次数       "))
        self.groupBox_A.setTitle(_translate("MainWindow", "选择亲代A"))
        self.selectfile1.setText(_translate("MainWindow", "选择文件"))
        self.file1_pre.setText(_translate("MainWindow", "预览"))
        self.groupBox_B.setTitle(_translate("MainWindow", "选择亲代B"))
        self.selectfile2.setText(_translate("MainWindow", "选择文件"))
        self.file2_pre.setText(_translate("MainWindow", "预览"))

    def openfilename1(self):
        fname = QFileDialog.getOpenFileName(self, '打开文件', './')
        self.file1_add.setText(fname[0])

    def openfilename2(self):
        fname = QFileDialog.getOpenFileName(self, '打开文件', './')
        self.file2_add.setText(fname[0])
